# 기본 설정
date_col: date
value_col: value
window: 24
horizon: 1
batch_size: 64
epochs: 10
lr: 0.001
hidden: 64
layers: 1
dropout: 0.0
seed: 42
model: lstm       # naive | seasonal_naive | moving_avg | arima | lstm
seasonal_m: 7     # seasonal naive 주기
ma_k: 5           # 이동평균 k
